In [9]:
import pandas as pd
import numpy as np

files = {
    "Monday": "../../data/raw/Monday-WorkingHours.pcap_ISCX.csv",
    "Tuesday": "../../data/raw/Tuesday-WorkingHours.pcap_ISCX.csv",
    "Wednesday": "../../data/raw/Wednesday-workingHours.pcap_ISCX.csv",
    "Thursday_AM": "../../data/raw/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    "Thursday_PM": "../../data/raw/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv",
    "Friday_AM": "../../data/raw/Friday-WorkingHours-Morning.pcap_ISCX.csv",
    "Friday_PortScan": "../../data/raw/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Friday_DDoS": "../../data/raw/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
}

In [12]:
dfs = {}

for name, path in files.items():
    df = pd.read_csv(path, low_memory=False)
    dfs[name] = df

In [15]:
'''
1. Dataset Schema Validation
'''
# Display shape and number of columns for every file

for name, df in dfs.items():
    print(f"{name:15} Rows: {df.shape[0]:,} | Columns: {df.shape[1]}")

reference_columns = list(dfs["Monday"].columns)

for name, df in dfs.items():
    same_schema = list(df.columns) == reference_columns
    print(f"{name:15} Same schema: {same_schema}")

for i, col in enumerate(dfs["Monday"].columns, start=1):
    print(f"{i:2}. {repr(col)}")

Monday          Rows: 529,918 | Columns: 79
Tuesday         Rows: 445,909 | Columns: 79
Wednesday       Rows: 692,703 | Columns: 79
Thursday_AM     Rows: 170,366 | Columns: 79
Thursday_PM     Rows: 288,602 | Columns: 79
Friday_AM       Rows: 191,033 | Columns: 79
Friday_PortScan Rows: 286,467 | Columns: 79
Friday_DDoS     Rows: 225,745 | Columns: 79
Monday          Same schema: True
Tuesday         Same schema: True
Wednesday       Same schema: True
Thursday_AM     Same schema: True
Thursday_PM     Same schema: True
Friday_AM       Same schema: True
Friday_PortScan Same schema: True
Friday_DDoS     Same schema: True
 1. ' Destination Port'
 2. ' Flow Duration'
 3. ' Total Fwd Packets'
 4. ' Total Backward Packets'
 5. 'Total Length of Fwd Packets'
 6. ' Total Length of Bwd Packets'
 7. ' Fwd Packet Length Max'
 8. ' Fwd Packet Length Min'
 9. ' Fwd Packet Length Mean'
10. ' Fwd Packet Length Std'
11. 'Bwd Packet Length Max'
12. ' Bwd Packet Length Min'
13. ' Bwd Packet Length Mean'
14. ' Bwd Packet Length Std'
15. 'Flow Bytes/s'
16. ' Flow Packets/s'
17. ' Flow IAT Mean'
18. ' Flow IAT Std'
19. ' Flow IAT Max'
20. ' Flow IAT Min'
21. 'Fwd IAT Total'
22. ' Fwd IAT Mean'
23. ' Fwd IAT Std'
24. ' Fwd IAT Max'
25. ' Fwd IAT Min'
26. 'Bwd IAT Total'
27. ' Bwd IAT Mean'
28. ' Bwd IAT Std'
29. ' Bwd IAT Max'
30. ' Bwd IAT Min'
31. 'Fwd PSH Flags'
32. ' Bwd PSH Flags'
33. ' Fwd URG Flags'
34. ' Bwd URG Flags'
35. ' Fwd Header Length'
36. ' Bwd Header Length'
37. 'Fwd Packets/s'
38. ' Bwd Packets/s'
39. ' Min Packet Length'
40. ' Max Packet Length'
41. ' Packet Length Mean'
42. ' Packet Length Std'
43. ' Packet Length Variance'
44. 'FIN Flag Count'
45. ' SYN Flag Count'
46. ' RST Flag Count'
47. ' PSH Flag Count'
48. ' ACK Flag Count'
49. ' URG Flag Count'
50. ' CWE Flag Count'
51. ' ECE Flag Count'
52. ' Down/Up Ratio'
53. ' Average Packet Size'
54. ' Avg Fwd Segment Size'
55. ' Avg Bwd Segment Size'
56. ' Fwd Header Length.1'
57. 'Fwd Avg Bytes/Bulk'
58. ' Fwd Avg Packets/Bulk'
59. ' Fwd Avg Bulk Rate'
60. ' Bwd Avg Bytes/Bulk'
61. ' Bwd Avg Packets/Bulk'
62. 'Bwd Avg Bulk Rate'
63. 'Subflow Fwd Packets'
64. ' Subflow Fwd Bytes'
65. ' Subflow Bwd Packets'
66. ' Subflow Bwd Bytes'
67. 'Init_Win_bytes_forward'
68. ' Init_Win_bytes_backward'
69. ' act_data_pkt_fwd'
70. ' min_seg_size_forward'
71. 'Active Mean'
72. ' Active Std'
73. ' Active Max'
74. ' Active Min'
75. 'Idle Mean'
76. ' Idle Std'
77. ' Idle Max'
78. ' Idle Min'
79. ' Label'

Leading spaces observed in features

In [17]:
'''
2. Column Name Cleaning
'''

for name, df in dfs.items():
    # Strip leading and trailing spaces from column names
    df.columns = df.columns.str.strip()

print(dfs["Monday"].columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

Verifying the schema after cleaning columns

In [19]:
'''
3. Verify Schema After Cleaning Columns
'''
reference_columns = list(dfs["Monday"].columns)

for name, df in dfs.items():
    same_schema = list(df.columns) == reference_columns
    print(f"{name:15} Same schema: {same_schema}")

Monday          Same schema: True
Tuesday         Same schema: True
Wednesday       Same schema: True
Thursday_AM     Same schema: True
Thursday_PM     Same schema: True
Friday_AM       Same schema: True
Friday_PortScan Same schema: True
Friday_DDoS     Same schema: True

In [20]:
dtype_summary = dfs["Monday"].dtypes.value_counts()

print(dtype_summary)

int64      54
float64    24
object      1
Name: count, dtype: int64

In [21]:
pd.DataFrame({
    "Column": dfs["Monday"].columns,
    "Data Type": dfs["Monday"].dtypes.values
})

                         Column Data Type
0              Destination Port     int64
1                 Flow Duration     int64
2             Total Fwd Packets     int64
3        Total Backward Packets     int64
4   Total Length of Fwd Packets     int64
..                          ...       ...
74                    Idle Mean   float64
75                     Idle Std   float64
76                     Idle Max     int64
77                     Idle Min     int64
78                        Label    object

[79 rows x 2 columns]

In [22]:
for name, df in dfs.items():
    print(f"\n{'='*60}")
    print(name)
    print(f"{'='*60}")

    print(df["Label"].value_counts())

============================================================
Monday
============================================================
Label
BENIGN    529918
Name: count, dtype: int64

============================================================
Tuesday
============================================================
Label
BENIGN         432074
FTP-Patator      7938
SSH-Patator      5897
Name: count, dtype: int64

============================================================
Wednesday
============================================================
Label
BENIGN              440031
DoS Hulk            231073
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Heartbleed              11
Name: count, dtype: int64

============================================================
Thursday_AM
============================================================
Label
BENIGN                        168186
Web Attack � Brute Force        1507
Web Attack � XSS                 652
Web Attack � Sql Injection        21
Name: count, dtype: int64

============================================================
Thursday_PM
============================================================
Label
BENIGN          288566
Infiltration        36
Name: count, dtype: int64

============================================================
Friday_AM
============================================================
Label
BENIGN    189067
Bot         1966
Name: count, dtype: int64

============================================================
Friday_PortScan
============================================================
Label
PortScan    158930
BENIGN      127537
Name: count, dtype: int64

============================================================
Friday_DDoS
============================================================
Label
DDoS      128027
BENIGN     97718
Name: count, dtype: int64

In [26]:
for name, df in dfs.items():
    print(name)
    for label in df["Label"].unique():
        print(repr(label))
    print("\n")

Monday
'BENIGN'


Tuesday
'BENIGN'
'FTP-Patator'
'SSH-Patator'


Wednesday
'BENIGN'
'DoS slowloris'
'DoS Slowhttptest'
'DoS Hulk'
'DoS GoldenEye'
'Heartbleed'


Thursday_AM
'BENIGN'
'Web Attack � Brute Force'
'Web Attack � XSS'
'Web Attack � Sql Injection'


Thursday_PM
'BENIGN'
'Infiltration'


Friday_AM
'BENIGN'
'Bot'


Friday_PortScan
'BENIGN'
'PortScan'


Friday_DDoS
'BENIGN'
'DDoS'

In [27]:
for name, df in dfs.items():
    df["Label"] = df["Label"].str.strip()

In [31]:
label_mapping = {
    "Web Attack � Brute Force": "Web Attack - Brute Force",
    "Web Attack � Sql Injection": "Web Attack - SQL Injection",
    "Web Attack � XSS": "Web Attack - XSS"
}

for name, df in dfs.items():
    df["Label"] = df["Label"].replace(label_mapping)

In [32]:
all_labels = set()

for df in dfs.values():
    all_labels.update(df["Label"].unique())

for label in sorted(all_labels):
    print(repr(label))

'BENIGN'
'Bot'
'DDoS'
'DoS GoldenEye'
'DoS Hulk'
'DoS Slowhttptest'
'DoS slowloris'
'FTP-Patator'
'Heartbleed'
'Infiltration'
'PortScan'
'SSH-Patator'
'Web Attack - Brute Force'
'Web Attack - SQL Injection'
'Web Attack - XSS'

In [33]:
for name, df in dfs.items():
    df["source_file"] = name

In [34]:
dfs["Monday"][["Label", "source_file"]].head()

    Label source_file
0  BENIGN      Monday
1  BENIGN      Monday
2  BENIGN      Monday
3  BENIGN      Monday
4  BENIGN      Monday

Combining all datasets

In [35]:
for name, df in dfs.items():
    df["source_file"] = name

data = pd.concat(dfs.values(), ignore_index=True)

print(f"Rows: {data.shape[0]:,}")
print(f"Columns: {data.shape[1]}")
print(f"Classes: {data['Label'].nunique()}")

Rows: 2,830,743
Columns: 80
Classes: 15

In [36]:
data["source_file"].value_counts()

source_file
Wednesday          692703
Monday             529918
Tuesday            445909
Thursday_PM        288602
Friday_PortScan    286467
Friday_DDoS        225745
Friday_AM          191033
Thursday_AM        170366
Name: count, dtype: int64

In [37]:
class_distribution = (
    data["Label"]
    .value_counts()
    .rename_axis("Class")
    .reset_index(name="Count")
)

class_distribution["Percentage"] = (
    class_distribution["Count"] / len(data) * 100
)

class_distribution["Percentage"] = (
    class_distribution["Percentage"].round(4)
)

class_distribution

                         Class    Count  Percentage
0                       BENIGN  2273097     80.3004
1                     DoS Hulk   231073      8.1630
2                     PortScan   158930      5.6144
3                         DDoS   128027      4.5227
4                DoS GoldenEye    10293      0.3636
5                  FTP-Patator     7938      0.2804
6                  SSH-Patator     5897      0.2083
7                DoS slowloris     5796      0.2048
8             DoS Slowhttptest     5499      0.1943
9                          Bot     1966      0.0695
10    Web Attack - Brute Force     1507      0.0532
11            Web Attack - XSS      652      0.0230
12                Infiltration       36      0.0013
13  Web Attack - SQL Injection       21      0.0007
14                  Heartbleed       11      0.0004

In [38]:
missing_count = data.isnull().sum()

missing_report = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": (
        missing_count / len(data) * 100
    )
})

missing_report = (
    missing_report[
        missing_report["Missing_Count"] > 0
    ]
    .sort_values("Missing_Count", ascending=False)
)

missing_report

              Missing_Count  Missing_Percentage
Flow Bytes/s           1358            0.047973

In [39]:
numeric_cols = data.select_dtypes(include=np.number).columns

pos_inf = np.isposinf(data[numeric_cols]).sum()
neg_inf = np.isneginf(data[numeric_cols]).sum()

inf_report = pd.DataFrame({
    "Positive_Inf": pos_inf,
    "Negative_Inf": neg_inf
})

inf_report["Total_Inf"] = (
    inf_report["Positive_Inf"] +
    inf_report["Negative_Inf"]
)

inf_report = (
    inf_report[
        inf_report["Total_Inf"] > 0
    ]
    .sort_values("Total_Inf", ascending=False)
)

inf_report

                Positive_Inf  Negative_Inf  Total_Inf
Flow Packets/s          2867             0       2867
Flow Bytes/s            1509             0       1509

In [40]:
duplicates_with_source = data.duplicated().sum()

print(
    f"Exact duplicates including source_file: "
    f"{duplicates_with_source:,}"
)

Exact duplicates including source_file: 256,479

In [41]:
original_cols = [
    col for col in data.columns
    if col != "source_file"
]

duplicates_without_source = (
    data.duplicated(subset=original_cols).sum()
)

print(
    f"Duplicates ignoring source_file: "
    f"{duplicates_without_source:,}"
)

Duplicates ignoring source_file: 308,381

In [42]:
duplicate_mask = data.duplicated(
    subset=original_cols,
    keep=False
)

data.loc[
    duplicate_mask,
    "Label"
].value_counts()

Label
BENIGN                      236257
PortScan                    101501
DoS Hulk                     59564
SSH-Patator                   2826
FTP-Patator                   2457
DoS slowloris                  507
DoS Slowhttptest               323
Web Attack - Brute Force        62
DDoS                            20
Bot                             19
DoS GoldenEye                   14
Name: count, dtype: int64

In [43]:
feature_cols = [
    col for col in data.columns
    if col not in ["Label", "source_file"]
]

unique_counts = data[feature_cols].nunique(dropna=False)

constant_features = (
    unique_counts[unique_counts <= 1]
    .sort_values()
)

constant_features

Bwd PSH Flags           1
Bwd URG Flags           1
Fwd Avg Bytes/Bulk      1
Fwd Avg Packets/Bulk    1
Fwd Avg Bulk Rate       1
Bwd Avg Bytes/Bulk      1
Bwd Avg Packets/Bulk    1
Bwd Avg Bulk Rate       1
dtype: int64

In [44]:
print(
    "Fwd Header Length.1 exists:",
    "Fwd Header Length.1" in data.columns
)

if "Fwd Header Length.1" in data.columns:
    same = data["Fwd Header Length"].equals(
        data["Fwd Header Length.1"]
    )

    print("Columns exactly identical:", same)

Fwd Header Length.1 exists: True
Columns exactly identical: True

In [45]:
non_numeric = data.select_dtypes(
    exclude=np.number
).columns.tolist()

print(non_numeric)

['Label', 'source_file']

Major observation:
- Fwd Header Length.1 is reduntant of Fwd Header Length ===> can remove
-